import type { FoodItem } from "@/src/types/app";

export const FOOD_DB: FoodItem[] = [
  {
    id: "egg-whites-raw",
    label: "Belanca jajeta",
    kind: "protein",
    priority: "tierA",
    basis: "raw",
    proteinPer100g: 11,
    caloriesPer100g: 52,
  },
  {
    id: "chicken-breast-raw",
    label: "Pileca prsa bez koze",
    kind: "protein",
    priority: "tierA",
    basis: "raw",
    proteinPer100g: 23,
    caloriesPer100g: 110,
  },
  {
    id: "turkey-breast-raw",
    label: "Cureca prsa bez koze",
    kind: "protein",
    priority: "tierA",
    basis: "raw",
    proteinPer100g: 24,
    caloriesPer100g: 114,
  },
  {
    id: "hake",
    label: "Oslic",
    kind: "protein",
    priority: "tierA",
    basis: "raw",
    proteinPer100g: 18,
    caloriesPer100g: 86,
  },
  {
    id: "tuna-brine",
    label: "Tunjevina u salamuri",
    kind: "protein",
    priority: "tierA",
    basis: "drained",
    proteinPer100g: 23,
    caloriesPer100g: 109,
  },
  {
    id: "ella-cheese",
    label: "Ella sir / obrani svezi sir",
    kind: "protein",
    priority: "tierA",
    basis: "asPackaged",
    proteinPer100g: 13,
    caloriesPer100g: 67,
  },
  {
    id: "greek-yogurt-0",
    label: "Grcki ili proteinski jogurt 0%",
    kind: "protein",
    priority: "tierA",
    basis: "asPackaged",
    proteinPer100g: 10,
    caloriesPer100g: 59,
  },
  {
    id: "sirloin-lean",
    label: "Ramstek lean",
    kind: "protein",
    priority: "tierB",
    basis: "raw",
    proteinPer100g: 22,
    caloriesPer100g: 135,
  },
  {
    id: "tenderloin-beef",
    label: "Biftek",
    kind: "protein",
    priority: "tierB",
    basis: "raw",
    proteinPer100g: 22,
    caloriesPer100g: 143,
  },
  {
    id: "beef-mince-95",
    label: "Mlevena junetina 95% lean",
    kind: "protein",
    priority: "tierB",
    basis: "raw",
    proteinPer100g: 21,
    caloriesPer100g: 137,
  },
  {
    id: "pork-tenderloin",
    label: "Svinjski file",
    kind: "protein",
    priority: "tierB",
    basis: "raw",
    proteinPer100g: 21,
    caloriesPer100g: 120,
  },
  {
    id: "shrimp",
    label: "Skampi",
    kind: "protein",
    priority: "tierB",
    basis: "raw",
    proteinPer100g: 20,
    caloriesPer100g: 99,
  },
  {
    id: "squid",
    label: "Lignje",
    kind: "protein",
    priority: "tierB",
    basis: "raw",
    proteinPer100g: 16,
    caloriesPer100g: 92,
  },
  {
    id: "protein-powder",
    label: "Protein prah",
    kind: "protein",
    priority: "limited",
    basis: "asPackaged",
    proteinPer100g: 80,
    caloriesPer100g: 390,
  },
  {
    id: "beef-jerky",
    label: "Juneci jerky",
    kind: "protein",
    priority: "limited",
    basis: "asPackaged",
    proteinPer100g: 33,
    caloriesPer100g: 250,
  },
  {
    id: "mushrooms",
    label: "Pecurke",
    kind: "vegetable",
    priority: "tierA",
    basis: "raw",
    proteinPer100g: 3,
    caloriesPer100g: 22,
  },
  {
    id: "broccoli",
    label: "Brokoli",
    kind: "vegetable",
    priority: "tierA",
    basis: "raw",
    proteinPer100g: 3,
    caloriesPer100g: 34,
  },
  {
    id: "cauliflower",
    label: "Karfiol",
    kind: "vegetable",
    priority: "tierA",
    basis: "raw",
    proteinPer100g: 2,
    caloriesPer100g: 25,
  },
  {
    id: "zucchini",
    label: "Tikvice",
    kind: "vegetable",
    priority: "tierA",
    basis: "raw",
    proteinPer100g: 1,
    caloriesPer100g: 17,
  },
  {
    id: "cucumber",
    label: "Krastavac",
    kind: "vegetable",
    priority: "tierA",
    basis: "raw",
    proteinPer100g: 1,
    caloriesPer100g: 15,
  },
  {
    id: "cabbage",
    label: "Kupus",
    kind: "vegetable",
    priority: "tierA",
    basis: "raw",
    proteinPer100g: 1,
    caloriesPer100g: 25,
  },
  {
    id: "baby-spinach",
    label: "Baby spanac",
    kind: "vegetable",
    priority: "tierA",
    basis: "raw",
    proteinPer100g: 3,
    caloriesPer100g: 23,
  },
  {
    id: "arugula",
    label: "Rukola",
    kind: "vegetable",
    priority: "tierA",
    basis: "raw",
    proteinPer100g: 3,
    caloriesPer100g: 25,
  },
  {
    id: "green-lettuce",
    label: "Zelena salata",
    kind: "vegetable",
    priority: "tierA",
    basis: "raw",
    proteinPer100g: 1,
    caloriesPer100g: 15,
  },
  {
    id: "iceberg",
    label: "Iceberg salata",
    kind: "vegetable",
    priority: "tierA",
    basis: "raw",
    proteinPer100g: 1,
    caloriesPer100g: 14,
  },
  {
    id: "leafy-mix",
    label: "Miks listova",
    kind: "vegetable",
    priority: "tierA",
    basis: "asPackaged",
    proteinPer100g: 2,
    caloriesPer100g: 18,
  },
  {
    id: "celery",
    label: "Celer stabljika",
    kind: "vegetable",
    priority: "tierA",
    basis: "raw",
    proteinPer100g: 1,
    caloriesPer100g: 14,
  },
  {
    id: "tomato",
    label: "Paradajz",
    kind: "vegetable",
    priority: "tierB",
    basis: "raw",
    proteinPer100g: 1,
    caloriesPer100g: 18,
  },
  {
    id: "cherry-tomato",
    label: "Ceri paradajz",
    kind: "vegetable",
    priority: "tierB",
    basis: "raw",
    proteinPer100g: 1,
    caloriesPer100g: 18,
  },
  {
    id: "onion",
    label: "Crni luk",
    kind: "vegetable",
    priority: "tierB",
    basis: "raw",
    proteinPer100g: 1,
    caloriesPer100g: 40,
  },
  {
    id: "spring-onion",
    label: "Mladi luk",
    kind: "vegetable",
    priority: "tierB",
    basis: "raw",
    proteinPer100g: 2,
    caloriesPer100g: 32,
  },
  {
    id: "pepper",
    label: "Paprika / babura",
    kind: "vegetable",
    priority: "tierB",
    basis: "raw",
    proteinPer100g: 1,
    caloriesPer100g: 31,
  },
  {
    id: "radish",
    label: "Rotkvice",
    kind: "vegetable",
    priority: "tierB",
    basis: "raw",
    proteinPer100g: 1,
    caloriesPer100g: 16,
  },
  {
    id: "roasted-pepper-jar",
    label: "Pecena paprika iz tegle",
    kind: "vegetable",
    priority: "tierB",
    basis: "drained",
    proteinPer100g: 1,
    caloriesPer100g: 31,
  },
  {
    id: "jar-mushrooms",
    label: "Sampinjoni iz tegle",
    kind: "vegetable",
    priority: "tierB",
    basis: "drained",
    proteinPer100g: 2,
    caloriesPer100g: 18,
  },
  {
    id: "peas",
    label: "Grasak",
    kind: "vegetable",
    priority: "limited",
    basis: "raw",
    proteinPer100g: 5,
    caloriesPer100g: 81,
  },
  {
    id: "corn",
    label: "Kukuruz",
    kind: "vegetable",
    priority: "limited",
    basis: "raw",
    proteinPer100g: 3,
    caloriesPer100g: 86,
  },
  {
    id: "carrot",
    label: "Sargarepa",
    kind: "vegetable",
    priority: "limited",
    basis: "raw",
    proteinPer100g: 1,
    caloriesPer100g: 41,
  },
  {
    id: "beetroot",
    label: "Cvekla",
    kind: "vegetable",
    priority: "limited",
    basis: "raw",
    proteinPer100g: 2,
    caloriesPer100g: 43,
  },
  {
    id: "potato",
    label: "Krompir",
    kind: "vegetable",
    priority: "limited",
    basis: "raw",
    proteinPer100g: 2,
    caloriesPer100g: 77,
  },
  {
    id: "pickles",
    label: "Kiseli krastavci",
    kind: "vegetable",
    priority: "tierB",
    basis: "drained",
    proteinPer100g: 1,
    caloriesPer100g: 12,
  },
  {
    id: "pickled-peppers",
    label: "Kisela paprika / feferoni",
    kind: "vegetable",
    priority: "tierB",
    basis: "drained",
    proteinPer100g: 1,
    caloriesPer100g: 24,
  },
  {
    id: "capers",
    label: "Kapari",
    kind: "condiment",
    priority: "condiment",
    basis: "drained",
    proteinPer100g: 2,
    caloriesPer100g: 23,
  },
  {
    id: "lemon-juice",
    label: "Limunov sok",
    kind: "condiment",
    priority: "condiment",
    basis: "asPackaged",
    proteinPer100g: 0,
    caloriesPer100g: 22,
  },
  {
    id: "soy-sauce",
    label: "Soja sos",
    kind: "condiment",
    priority: "condiment",
    basis: "asPackaged",
    proteinPer100g: 8,
    caloriesPer100g: 53,
  },
  {
    id: "mustard",
    label: "Senf",
    kind: "condiment",
    priority: "condiment",
    basis: "asPackaged",
    proteinPer100g: 4,
    caloriesPer100g: 66,
  },
  {
    id: "salsa",
    label: "Salsa / pico",
    kind: "condiment",
    priority: "condiment",
    basis: "asPackaged",
    proteinPer100g: 1,
    caloriesPer100g: 29,
  },
  {
    id: "vinegar",
    label: "Sirce",
    kind: "condiment",
    priority: "condiment",
    basis: "asPackaged",
    proteinPer100g: 0,
    caloriesPer100g: 18,
  },
];
