import type { FoodItem } from "@/src/types/app";

export const FOOD_DB: FoodItem[] = [
  {
    id: "egg-whites-raw",
    label: "Belanca jajeta",
    kind: "protein",
    priority: "tierA",
    basis: "raw",
    proteinPer100g: 11,
    carbsPer100g: 0.7,
    fatPer100g: 0.2,
    caloriesPer100g: 52,
  },
  {
    id: "chicken-breast-raw",
    label: "Pileca prsa bez koze",
    kind: "protein",
    priority: "tierA",
    basis: "raw",
    proteinPer100g: 23,
    carbsPer100g: 0,
    fatPer100g: 1.6,
    caloriesPer100g: 110,
  },
  {
    id: "turkey-breast-raw",
    label: "Cureca prsa bez koze",
    kind: "protein",
    priority: "tierA",
    basis: "raw",
    proteinPer100g: 24,
    carbsPer100g: 0,
    fatPer100g: 1.2,
    caloriesPer100g: 114,
  },
  {
    id: "hake",
    label: "Oslic",
    kind: "protein",
    priority: "tierA",
    basis: "raw",
    proteinPer100g: 18,
    carbsPer100g: 0,
    fatPer100g: 1.4,
    caloriesPer100g: 86,
  },
  {
    id: "cod",
    label: "Bakalar / beli morski file",
    kind: "protein",
    priority: "tierA",
    basis: "raw",
    proteinPer100g: 18,
    carbsPer100g: 0,
    fatPer100g: 0.7,
    caloriesPer100g: 82,
  },
  {
    id: "tuna-brine",
    label: "Tunjevina u salamuri",
    kind: "protein",
    priority: "tierA",
    basis: "drained",
    proteinPer100g: 23,
    carbsPer100g: 0,
    fatPer100g: 1,
    caloriesPer100g: 109,
  },
  {
    id: "ella-cheese",
    label: "Imlek Ella sir 0% / obrani svezi sir",
    kind: "protein",
    priority: "tierA",
    basis: "asPackaged",
    proteinPer100g: 13,
    carbsPer100g: 3.5,
    fatPer100g: 0.5,
    caloriesPer100g: 67,
  },
  {
    id: "ella-cheese-protein",
    label: "Imlek Ella Protein sir",
    kind: "protein",
    priority: "tierA",
    basis: "asPackaged",
    proteinPer100g: 16,
    carbsPer100g: 3.5,
    fatPer100g: 0.5,
    caloriesPer100g: 83,
  },
  {
    id: "z-bregov-skyr-natur",
    label: "Z bregov Protein skyr natur",
    kind: "protein",
    priority: "tierA",
    basis: "asPackaged",
    proteinPer100g: 11,
    carbsPer100g: 4,
    fatPer100g: 0.2,
    caloriesPer100g: 62,
  },
  {
    id: "pilos-skyr-natural",
    label: "Pilos / Lidl skyr natur",
    kind: "protein",
    priority: "tierA",
    basis: "asPackaged",
    proteinPer100g: 11,
    carbsPer100g: 4,
    fatPer100g: 0.2,
    caloriesPer100g: 63,
  },
  {
    id: "imlek-protein-skyr",
    label: "Imlek Protein skyr / proteinski jogurt",
    kind: "protein",
    priority: "tierA",
    basis: "asPackaged",
    proteinPer100g: 10,
    carbsPer100g: 4,
    fatPer100g: 0.5,
    caloriesPer100g: 62,
  },
  {
    id: "greek-yogurt-0",
    label: "Grcki jogurt 0%",
    kind: "protein",
    priority: "tierA",
    basis: "asPackaged",
    proteinPer100g: 10,
    carbsPer100g: 3.6,
    fatPer100g: 0.4,
    caloriesPer100g: 59,
  },
  {
    id: "low-fat-cottage",
    label: "Cottage cheese light",
    kind: "protein",
    priority: "tierA",
    basis: "asPackaged",
    proteinPer100g: 12,
    carbsPer100g: 3,
    fatPer100g: 2,
    caloriesPer100g: 78,
  },
  {
    id: "president-cottage-light",
    label: "President cottage sir light",
    kind: "protein",
    priority: "tierA",
    basis: "asPackaged",
    proteinPer100g: 12,
    carbsPer100g: 3,
    fatPer100g: 2.5,
    caloriesPer100g: 82,
  },
  {
    id: "dr-milk-sitan-sir-fit",
    label: "Dr Milk sitan sir fit",
    kind: "protein",
    priority: "tierA",
    basis: "asPackaged",
    proteinPer100g: 14,
    carbsPer100g: 3,
    fatPer100g: 1.5,
    caloriesPer100g: 82,
  },
  {
    id: "moj-mlek-sitni-sir-light",
    label: "Moja Kravica / light svezi sir",
    kind: "protein",
    priority: "tierA",
    basis: "asPackaged",
    proteinPer100g: 12,
    carbsPer100g: 3,
    fatPer100g: 1,
    caloriesPer100g: 70,
  },
  {
    id: "sirloin-lean",
    label: "Ramstek lean",
    kind: "protein",
    priority: "tierB",
    basis: "raw",
    proteinPer100g: 22,
    carbsPer100g: 0,
    fatPer100g: 5,
    caloriesPer100g: 135,
  },
  {
    id: "tenderloin-beef",
    label: "Biftek",
    kind: "protein",
    priority: "tierB",
    basis: "raw",
    proteinPer100g: 22,
    carbsPer100g: 0,
    fatPer100g: 6,
    caloriesPer100g: 143,
  },
  {
    id: "beef-mince-95",
    label: "Mlevena junetina 95% lean",
    kind: "protein",
    priority: "tierB",
    basis: "raw",
    proteinPer100g: 21,
    carbsPer100g: 0,
    fatPer100g: 5,
    caloriesPer100g: 137,
  },
  {
    id: "pork-tenderloin",
    label: "Svinjski file",
    kind: "protein",
    priority: "tierB",
    basis: "raw",
    proteinPer100g: 21,
    carbsPer100g: 0,
    fatPer100g: 4,
    caloriesPer100g: 120,
  },
  {
    id: "shrimp",
    label: "Skampi",
    kind: "protein",
    priority: "tierB",
    basis: "raw",
    proteinPer100g: 20,
    carbsPer100g: 0.2,
    fatPer100g: 0.5,
    caloriesPer100g: 99,
  },
  {
    id: "squid",
    label: "Lignje",
    kind: "protein",
    priority: "tierB",
    basis: "raw",
    proteinPer100g: 16,
    carbsPer100g: 3,
    fatPer100g: 1.4,
    caloriesPer100g: 92,
  },
  {
    id: "protein-powder",
    label: "Protein prah",
    kind: "protein",
    priority: "limited",
    basis: "asPackaged",
    proteinPer100g: 80,
    carbsPer100g: 7,
    fatPer100g: 6,
    caloriesPer100g: 390,
  },
  {
    id: "beef-jerky",
    label: "Juneci jerky",
    kind: "protein",
    priority: "limited",
    basis: "asPackaged",
    proteinPer100g: 33,
    carbsPer100g: 18,
    fatPer100g: 5,
    caloriesPer100g: 250,
  },
  {
    id: "mushrooms",
    label: "Pecurke",
    kind: "vegetable",
    priority: "tierA",
    basis: "raw",
    proteinPer100g: 3.1,
    carbsPer100g: 3.3,
    fatPer100g: 0.3,
    caloriesPer100g: 22,
  },
  {
    id: "broccoli",
    label: "Brokoli",
    kind: "vegetable",
    priority: "tierA",
    basis: "raw",
    proteinPer100g: 2.8,
    carbsPer100g: 6.6,
    fatPer100g: 0.4,
    caloriesPer100g: 34,
  },
  {
    id: "cauliflower",
    label: "Karfiol",
    kind: "vegetable",
    priority: "tierA",
    basis: "raw",
    proteinPer100g: 1.9,
    carbsPer100g: 5,
    fatPer100g: 0.3,
    caloriesPer100g: 25,
  },
  {
    id: "zucchini",
    label: "Tikvice",
    kind: "vegetable",
    priority: "tierA",
    basis: "raw",
    proteinPer100g: 1.2,
    carbsPer100g: 3.1,
    fatPer100g: 0.3,
    caloriesPer100g: 17,
  },
  {
    id: "cucumber",
    label: "Krastavac",
    kind: "vegetable",
    priority: "tierA",
    basis: "raw",
    proteinPer100g: 0.7,
    carbsPer100g: 3.6,
    fatPer100g: 0.1,
    caloriesPer100g: 15,
  },
  {
    id: "cabbage",
    label: "Kupus",
    kind: "vegetable",
    priority: "tierA",
    basis: "raw",
    proteinPer100g: 1.3,
    carbsPer100g: 5.8,
    fatPer100g: 0.1,
    caloriesPer100g: 25,
  },
  {
    id: "baby-spinach",
    label: "Baby spanac",
    kind: "vegetable",
    priority: "tierA",
    basis: "raw",
    proteinPer100g: 2.9,
    carbsPer100g: 3.6,
    fatPer100g: 0.4,
    caloriesPer100g: 23,
  },
  {
    id: "arugula",
    label: "Rukola",
    kind: "vegetable",
    priority: "tierA",
    basis: "raw",
    proteinPer100g: 2.6,
    carbsPer100g: 3.7,
    fatPer100g: 0.7,
    caloriesPer100g: 25,
  },
  {
    id: "green-lettuce",
    label: "Zelena salata",
    kind: "vegetable",
    priority: "tierA",
    basis: "raw",
    proteinPer100g: 1.4,
    carbsPer100g: 2.9,
    fatPer100g: 0.2,
    caloriesPer100g: 15,
  },
  {
    id: "iceberg",
    label: "Iceberg salata",
    kind: "vegetable",
    priority: "tierA",
    basis: "raw",
    proteinPer100g: 0.9,
    carbsPer100g: 3,
    fatPer100g: 0.1,
    caloriesPer100g: 14,
  },
  {
    id: "leafy-mix",
    label: "Miks listova",
    kind: "vegetable",
    priority: "tierA",
    basis: "asPackaged",
    proteinPer100g: 1.8,
    carbsPer100g: 3,
    fatPer100g: 0.3,
    caloriesPer100g: 18,
  },
  {
    id: "celery",
    label: "Celer stabljika",
    kind: "vegetable",
    priority: "tierA",
    basis: "raw",
    proteinPer100g: 0.7,
    carbsPer100g: 3,
    fatPer100g: 0.2,
    caloriesPer100g: 14,
  },
  {
    id: "frikom-brokoli",
    label: "Frikom brokoli zamrznuti",
    kind: "vegetable",
    priority: "tierA",
    basis: "asPackaged",
    proteinPer100g: 2.8,
    carbsPer100g: 4,
    fatPer100g: 0.4,
    caloriesPer100g: 34,
  },
  {
    id: "frikom-karfiol",
    label: "Frikom karfiol zamrznuti",
    kind: "vegetable",
    priority: "tierA",
    basis: "asPackaged",
    proteinPer100g: 1.9,
    carbsPer100g: 4,
    fatPer100g: 0.3,
    caloriesPer100g: 28,
  },
  {
    id: "frikom-spanac-briketi",
    label: "Frikom spanac briketi",
    kind: "vegetable",
    priority: "tierA",
    basis: "asPackaged",
    proteinPer100g: 2.6,
    carbsPer100g: 3,
    fatPer100g: 0.4,
    caloriesPer100g: 27,
  },
  {
    id: "freshona-brokoli",
    label: "Freshona / Lidl brokoli zamrznuti",
    kind: "vegetable",
    priority: "tierA",
    basis: "asPackaged",
    proteinPer100g: 2.8,
    carbsPer100g: 4,
    fatPer100g: 0.4,
    caloriesPer100g: 34,
  },
  {
    id: "premia-brokoli",
    label: "Premia / Maxi brokoli zamrznuti",
    kind: "vegetable",
    priority: "tierA",
    basis: "asPackaged",
    proteinPer100g: 2.8,
    carbsPer100g: 4,
    fatPer100g: 0.4,
    caloriesPer100g: 34,
  },
  {
    id: "kplus-brokoli",
    label: "K Plus / IDEA brokoli zamrznuti",
    kind: "vegetable",
    priority: "tierA",
    basis: "asPackaged",
    proteinPer100g: 2.8,
    carbsPer100g: 4,
    fatPer100g: 0.4,
    caloriesPer100g: 34,
  },
  {
    id: "tomato",
    label: "Paradajz",
    kind: "vegetable",
    priority: "tierB",
    basis: "raw",
    proteinPer100g: 0.9,
    carbsPer100g: 3.9,
    fatPer100g: 0.2,
    caloriesPer100g: 18,
  },
  {
    id: "cherry-tomato",
    label: "Ceri paradajz",
    kind: "vegetable",
    priority: "tierB",
    basis: "raw",
    proteinPer100g: 0.9,
    carbsPer100g: 3.9,
    fatPer100g: 0.2,
    caloriesPer100g: 18,
  },
  {
    id: "onion",
    label: "Crni luk",
    kind: "vegetable",
    priority: "tierB",
    basis: "raw",
    proteinPer100g: 1.1,
    carbsPer100g: 9.3,
    fatPer100g: 0.1,
    caloriesPer100g: 40,
  },
  {
    id: "spring-onion",
    label: "Mladi luk",
    kind: "vegetable",
    priority: "tierB",
    basis: "raw",
    proteinPer100g: 1.8,
    carbsPer100g: 7.3,
    fatPer100g: 0.2,
    caloriesPer100g: 32,
  },
  {
    id: "pepper",
    label: "Paprika / babura",
    kind: "vegetable",
    priority: "tierB",
    basis: "raw",
    proteinPer100g: 1,
    carbsPer100g: 6,
    fatPer100g: 0.3,
    caloriesPer100g: 31,
  },
  {
    id: "radish",
    label: "Rotkvice",
    kind: "vegetable",
    priority: "tierB",
    basis: "raw",
    proteinPer100g: 0.7,
    carbsPer100g: 3.4,
    fatPer100g: 0.1,
    caloriesPer100g: 16,
  },
  {
    id: "roasted-pepper-jar",
    label: "Pecena paprika iz tegle",
    kind: "vegetable",
    priority: "tierB",
    basis: "drained",
    proteinPer100g: 1,
    carbsPer100g: 6,
    fatPer100g: 0.3,
    caloriesPer100g: 31,
  },
  {
    id: "jar-mushrooms",
    label: "Sampinjoni iz tegle",
    kind: "vegetable",
    priority: "tierB",
    basis: "drained",
    proteinPer100g: 2,
    carbsPer100g: 2.7,
    fatPer100g: 0.3,
    caloriesPer100g: 18,
  },
  {
    id: "pickles",
    label: "Kiseli krastavci",
    kind: "vegetable",
    priority: "tierB",
    basis: "drained",
    proteinPer100g: 0.6,
    carbsPer100g: 2.4,
    fatPer100g: 0.2,
    caloriesPer100g: 12,
  },
  {
    id: "pickled-peppers",
    label: "Kisela paprika / feferoni",
    kind: "vegetable",
    priority: "tierB",
    basis: "drained",
    proteinPer100g: 1,
    carbsPer100g: 5,
    fatPer100g: 0.2,
    caloriesPer100g: 24,
  },
  {
    id: "frikom-provansa",
    label: "Frikom Provansa mesavina povrca",
    kind: "vegetable",
    priority: "tierB",
    basis: "asPackaged",
    proteinPer100g: 2,
    carbsPer100g: 6,
    fatPer100g: 0.5,
    caloriesPer100g: 38,
  },
  {
    id: "frikom-gril-povrce",
    label: "Frikom gril povrce",
    kind: "vegetable",
    priority: "tierB",
    basis: "asPackaged",
    proteinPer100g: 1.6,
    carbsPer100g: 7,
    fatPer100g: 0.5,
    caloriesPer100g: 42,
  },
  {
    id: "frikom-minestrone",
    label: "Frikom Minestrone mesavina",
    kind: "vegetable",
    priority: "tierB",
    basis: "asPackaged",
    proteinPer100g: 2.2,
    carbsPer100g: 8,
    fatPer100g: 0.4,
    caloriesPer100g: 48,
  },
  {
    id: "freshona-wok-mix",
    label: "Freshona / Lidl Wok mix",
    kind: "vegetable",
    priority: "tierB",
    basis: "asPackaged",
    proteinPer100g: 2,
    carbsPer100g: 7,
    fatPer100g: 0.5,
    caloriesPer100g: 42,
  },
  {
    id: "freshona-italian-mix",
    label: "Freshona / Lidl italijanska mesavina",
    kind: "vegetable",
    priority: "tierB",
    basis: "asPackaged",
    proteinPer100g: 1.8,
    carbsPer100g: 6,
    fatPer100g: 0.5,
    caloriesPer100g: 38,
  },
  {
    id: "premia-mediteran-mix",
    label: "Premia / Maxi mediteran mesavina",
    kind: "vegetable",
    priority: "tierB",
    basis: "asPackaged",
    proteinPer100g: 1.7,
    carbsPer100g: 6,
    fatPer100g: 0.5,
    caloriesPer100g: 38,
  },
  {
    id: "kplus-carska-mesavina",
    label: "K Plus / IDEA carska mesavina",
    kind: "vegetable",
    priority: "limited",
    basis: "asPackaged",
    proteinPer100g: 3,
    carbsPer100g: 11,
    fatPer100g: 0.5,
    caloriesPer100g: 62,
  },
  {
    id: "frikom-carska-mesavina",
    label: "Frikom carska mesavina",
    kind: "vegetable",
    priority: "limited",
    basis: "asPackaged",
    proteinPer100g: 3,
    carbsPer100g: 11,
    fatPer100g: 0.5,
    caloriesPer100g: 62,
  },
  {
    id: "frikom-zlatna-mesavina",
    label: "Frikom zlatna mesavina",
    kind: "vegetable",
    priority: "limited",
    basis: "asPackaged",
    proteinPer100g: 3.5,
    carbsPer100g: 15,
    fatPer100g: 0.7,
    caloriesPer100g: 82,
  },
  {
    id: "frikom-mexican-mix",
    label: "Frikom meksicka mesavina",
    kind: "vegetable",
    priority: "limited",
    basis: "asPackaged",
    proteinPer100g: 4,
    carbsPer100g: 14,
    fatPer100g: 0.7,
    caloriesPer100g: 80,
  },
  {
    id: "frikom-russian-salad-mix",
    label: "Frikom povrce za rusku salatu",
    kind: "vegetable",
    priority: "limited",
    basis: "asPackaged",
    proteinPer100g: 3,
    carbsPer100g: 13,
    fatPer100g: 0.4,
    caloriesPer100g: 70,
  },
  {
    id: "peas",
    label: "Grasak",
    kind: "vegetable",
    priority: "limited",
    basis: "raw",
    proteinPer100g: 5,
    carbsPer100g: 14,
    fatPer100g: 0.4,
    caloriesPer100g: 81,
  },
  {
    id: "corn",
    label: "Kukuruz",
    kind: "vegetable",
    priority: "limited",
    basis: "raw",
    proteinPer100g: 3.2,
    carbsPer100g: 19,
    fatPer100g: 1.2,
    caloriesPer100g: 86,
  },
  {
    id: "carrot",
    label: "Sargarepa",
    kind: "vegetable",
    priority: "limited",
    basis: "raw",
    proteinPer100g: 0.9,
    carbsPer100g: 9.6,
    fatPer100g: 0.2,
    caloriesPer100g: 41,
  },
  {
    id: "beetroot",
    label: "Cvekla",
    kind: "vegetable",
    priority: "limited",
    basis: "raw",
    proteinPer100g: 1.6,
    carbsPer100g: 10,
    fatPer100g: 0.2,
    caloriesPer100g: 43,
  },
  {
    id: "potato",
    label: "Krompir",
    kind: "vegetable",
    priority: "limited",
    basis: "raw",
    proteinPer100g: 2,
    carbsPer100g: 17,
    fatPer100g: 0.1,
    caloriesPer100g: 77,
  },
  {
    id: "frikom-sumsko-voce",
    label: "Frikom sumsko voce zamrznuto",
    kind: "fruit",
    priority: "limited",
    basis: "asPackaged",
    proteinPer100g: 1,
    carbsPer100g: 10,
    fatPer100g: 0.5,
    caloriesPer100g: 50,
  },
  {
    id: "frikom-malina",
    label: "Frikom malina zamrznuta",
    kind: "fruit",
    priority: "limited",
    basis: "asPackaged",
    proteinPer100g: 1.2,
    carbsPer100g: 12,
    fatPer100g: 0.7,
    caloriesPer100g: 52,
  },
  {
    id: "frikom-borovnica",
    label: "Frikom borovnica zamrznuta",
    kind: "fruit",
    priority: "limited",
    basis: "asPackaged",
    proteinPer100g: 0.7,
    carbsPer100g: 14.5,
    fatPer100g: 0.3,
    caloriesPer100g: 57,
  },
  {
    id: "frikom-jagoda",
    label: "Frikom jagoda zamrznuta",
    kind: "fruit",
    priority: "limited",
    basis: "asPackaged",
    proteinPer100g: 0.7,
    carbsPer100g: 7.7,
    fatPer100g: 0.3,
    caloriesPer100g: 35,
  },
  {
    id: "frikom-visnja",
    label: "Frikom visnja zamrznuta",
    kind: "fruit",
    priority: "limited",
    basis: "asPackaged",
    proteinPer100g: 1,
    carbsPer100g: 12,
    fatPer100g: 0.3,
    caloriesPer100g: 50,
  },
  {
    id: "freshona-berry-mix",
    label: "Freshona / Lidl berry mix zamrznut",
    kind: "fruit",
    priority: "limited",
    basis: "asPackaged",
    proteinPer100g: 1,
    carbsPer100g: 10,
    fatPer100g: 0.5,
    caloriesPer100g: 50,
  },
  {
    id: "freshona-strawberry",
    label: "Freshona / Lidl jagoda zamrznuta",
    kind: "fruit",
    priority: "limited",
    basis: "asPackaged",
    proteinPer100g: 0.7,
    carbsPer100g: 7.7,
    fatPer100g: 0.3,
    caloriesPer100g: 35,
  },
  {
    id: "premia-forest-fruit",
    label: "Premia / Maxi sumsko voce",
    kind: "fruit",
    priority: "limited",
    basis: "asPackaged",
    proteinPer100g: 1,
    carbsPer100g: 10,
    fatPer100g: 0.5,
    caloriesPer100g: 50,
  },
  {
    id: "kplus-forest-fruit",
    label: "K Plus / IDEA sumsko voce",
    kind: "fruit",
    priority: "limited",
    basis: "asPackaged",
    proteinPer100g: 1,
    carbsPer100g: 10,
    fatPer100g: 0.5,
    caloriesPer100g: 50,
  },
  {
    id: "banana",
    label: "Banana",
    kind: "fruit",
    priority: "limited",
    basis: "raw",
    proteinPer100g: 1.1,
    carbsPer100g: 22.8,
    fatPer100g: 0.3,
    caloriesPer100g: 89,
  },
  {
    id: "apple",
    label: "Jabuka",
    kind: "fruit",
    priority: "limited",
    basis: "raw",
    proteinPer100g: 0.3,
    carbsPer100g: 13.8,
    fatPer100g: 0.2,
    caloriesPer100g: 52,
  },
  {
    id: "capers",
    label: "Kapari",
    kind: "condiment",
    priority: "condiment",
    basis: "drained",
    proteinPer100g: 2.4,
    carbsPer100g: 4.9,
    fatPer100g: 0.9,
    caloriesPer100g: 23,
  },
  {
    id: "lemon-juice",
    label: "Limunov sok",
    kind: "condiment",
    priority: "condiment",
    basis: "asPackaged",
    proteinPer100g: 0.4,
    carbsPer100g: 6.9,
    fatPer100g: 0.2,
    caloriesPer100g: 22,
  },
  {
    id: "soy-sauce",
    label: "Soja sos",
    kind: "condiment",
    priority: "condiment",
    basis: "asPackaged",
    proteinPer100g: 8,
    carbsPer100g: 4.9,
    fatPer100g: 0.6,
    caloriesPer100g: 53,
  },
  {
    id: "mustard",
    label: "Senf",
    kind: "condiment",
    priority: "condiment",
    basis: "asPackaged",
    proteinPer100g: 4,
    carbsPer100g: 5.8,
    fatPer100g: 4,
    caloriesPer100g: 66,
  },
  {
    id: "salsa",
    label: "Salsa / pico",
    kind: "condiment",
    priority: "condiment",
    basis: "asPackaged",
    proteinPer100g: 1.5,
    carbsPer100g: 6.6,
    fatPer100g: 0.2,
    caloriesPer100g: 29,
  },
  {
    id: "vinegar",
    label: "Sirce",
    kind: "condiment",
    priority: "condiment",
    basis: "asPackaged",
    proteinPer100g: 0,
    carbsPer100g: 0.9,
    fatPer100g: 0,
    caloriesPer100g: 18,
  },
];
